/*  Georgia State University
 *  CSC 8840 - Modeling and Simulation Theory and Application
 *  This java class is part of a class project that involves using particle filter 
 *  to carry out data assimilation for a DEVS-based discrete event simulation model
 *
 *  Author    : Prof. Xiaolin Hu
 *  Date      : 10-14-2024
 */


package PFDataAssimilation;

import simView.*;

import java.awt.*;
import java.io.*;
import genDevs.modeling.*;
import genDevs.simulation.*;
import GenCol.*;


public class carWashSys_Real extends ViewableDigraph{


public carWashSys_Real(){
    this("carWashSys");
}

public carWashSys_Real(String nm){
    super(nm);
    carWashSysConstruct();
}

public void carWashSysConstruct(){

    this.addOutport("out");

    ViewableAtomic car_genr = new carGenr("carGenr");
    ViewableAtomic wash_center = new carWashCenter_VaryingSchedule("CWC_VaryingSchedule");
    ViewableAtomic trand = new transducer_Real_dataSaving ();

     add(car_genr);
     add(wash_center);
     add(trand);

     addCoupling(car_genr,"out",wash_center,"carIn");
     addCoupling(car_genr,"out",trand,"ariv");
     addCoupling(wash_center,"out",trand,"solved");
     addCoupling(wash_center,"out",this,"out");

     addCoupling(trand,"out",wash_center,"report");
     addCoupling(wash_center,"report_out",trand,"report_in");

}


    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(934, 453);
        if((ViewableComponent)withName("transd")!=null)
             ((ViewableComponent)withName("transd")).setPreferredLocation(new Point(335, 45));
        if((ViewableComponent)withName("carGenr")!=null)
             ((ViewableComponent)withName("carGenr")).setPreferredLocation(new Point(141, 84));
        if((ViewableComponent)withName("CWC_VaryingSchedule")!=null)
             ((ViewableComponent)withName("CWC_VaryingSchedule")).setPreferredLocation(new Point(280, 250));
    }
}
