/*  Georgia State University
 *  CSC 8840 - Modeling and Simulation Theory and Application
 *  This java class is part of a class project that involves using particle filter 
 *  to carry out data assimilation for a DEVS-based discrete event simulation model
 *
 *  Author    : Prof. Xiaolin Hu
 *  Date      : 10-14-2024
 */


package PFDataAssimilation;

import simView.*;

import java.awt.*;
import java.io.*;
import java.util.Random;

import genDevs.modeling.*;
import genDevs.simulation.*;
import GenCol.*;


public class carWashSys_DA extends ViewableDigraph{

	transducer_DA trand;

public carWashSys_DA(){
    this("carWashSys");
}

public carWashSys_DA(String nm) {
	this(nm, 0, "working_passive", configData.schedule_workingDuration_emptyQueue, 0, new Random(configData.PF_globalRandSeed));
}

public carWashSys_DA(String nm, int QSize, String State, double Sigma, double initElapsedTimeInPhase, Random rd){
    super(nm);
    carWashSysConstruct(QSize, State, Sigma, initElapsedTimeInPhase, rd);
}

public void carWashSysConstruct(int QSize, String State, double Sigma, double initElapsedTimeInPhase, Random rd){

    this.addOutport("out");

    ViewableAtomic car_genr = new carGenr("carGenr", rd);
    ViewableAtomic wash_center = new carWashCenter_VaryingSchedule("CWC_VaryingSchedule", QSize, State, Sigma, initElapsedTimeInPhase, rd);
    trand = new transducer_DA ();

     add(car_genr);
     add(wash_center);
     add(trand);

     addCoupling(car_genr,"out",wash_center,"carIn");
     addCoupling(car_genr,"out",trand,"ariv");
     addCoupling(wash_center,"out",trand,"solved");
     addCoupling(wash_center,"out",this,"out");

     addCoupling(trand,"out",wash_center,"report");
     addCoupling(wash_center,"report_out",trand,"report_in");

}


    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(934, 453);
        if((ViewableComponent)withName("transd")!=null)
             ((ViewableComponent)withName("transd")).setPreferredLocation(new Point(319, 65));
        if((ViewableComponent)withName("CWC_VaryingSchedule")!=null)
             ((ViewableComponent)withName("CWC_VaryingSchedule")).setPreferredLocation(new Point(286, 253));
        if((ViewableComponent)withName("carGenr")!=null)
             ((ViewableComponent)withName("carGenr")).setPreferredLocation(new Point(66, 150));
    }
}
