
package  oneDCellSpace;

import java.lang.*;
import java.awt.*;
import java.io.*;
import java.util.*;
import GenCol.*;
import util.*;
import simView.*;



public class minTreeExample extends minTree {



public minTreeExample(){
this("minTreeExample");
}

public minTreeExample(String nm){
super(nm);

addMinSelect("m1",1);
addMinSelect("m2",1.2);
addMinSelect("h1", new String[]{"m1","m2"});

addMinSelect("n1",2.1);//1.0000000102);
addMinSelect("n2",2.2);
addMinSelect("h2", new String[]{"n1","n2"});

addMinSelect("h3", new String[]{"h1","h2"});

addMinSelect("o1",3);
addMinSelect("o2",3.2);
addMinSelect("h4", new String[]{"o1","o2"});

addMinSelect("p1",4.1);//1.0000000102);
addMinSelect("p2",4.2);
addMinSelect("h5", new String[]{"p1","p2"});

addMinSelect("h6", new String[]{"h5","h4"});

addRootMinSelect("h7", new String[]{"h3","h6"});

doCoupling();
}


    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(1012, 625);
        ((ViewableComponent)withName("h6")).setPreferredLocation(new Point(444, 411));
        ((ViewableComponent)withName("p1")).setPreferredLocation(new Point(52, 493));
        ((ViewableComponent)withName("h4")).setPreferredLocation(new Point(253, 377));
        ((ViewableComponent)withName("h3")).setPreferredLocation(new Point(408, 177));
        ((ViewableComponent)withName("n2")).setPreferredLocation(new Point(51, 316));
        ((ViewableComponent)withName("h1")).setPreferredLocation(new Point(221, 100));
        ((ViewableComponent)withName("o2")).setPreferredLocation(new Point(52, 440));
        ((ViewableComponent)withName("h7")).setPreferredLocation(new Point(601, 281));
        ((ViewableComponent)withName("m1")).setPreferredLocation(new Point(57, 65));
        ((ViewableComponent)withName("h2")).setPreferredLocation(new Point(238, 233));
        ((ViewableComponent)withName("p2")).setPreferredLocation(new Point(53, 556));
        ((ViewableComponent)withName("o1")).setPreferredLocation(new Point(52, 384));
        ((ViewableComponent)withName("n1")).setPreferredLocation(new Point(51, 239));
        ((ViewableComponent)withName("m2")).setPreferredLocation(new Point(53, 157));
        ((ViewableComponent)withName("h5")).setPreferredLocation(new Point(265, 491));
    }
}
