
package oneDCellSpace;

import java.lang.*;
import java.awt.*;
import java.io.*;
import java.util.*;
import simView.*;
import genDevs.modeling.*;
import genDevs.simulation.*;
import GenCol.*;
import genDevs.plots.*;
import util.*;
import oneDCellSpace.*;


public class pipeLineRandOpt extends ViewableDigraph{



public pipeLineRandOpt(){
this("pipeLineRandOpt",25);
}

public pipeLineRandOpt(String nm,int maxCells){
super(nm);
addInport("in");
addOutport("out");


for (int i = 1;i<= maxCells;i++){
ViewableDigraph w = new pipeLineRand(4*i);
add(w);
w.setPreferredLocation(new Point(50, 20 + (int)(i*60)));

//w.setBlackBox(true);
//w.setHidden(true);


}
}


    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(885, 1473);
        ((ViewableComponent)withName("pipeLineRand 96")).setPreferredLocation(new Point(394, 1102));
        ((ViewableComponent)withName("pipeLineRand 56")).setPreferredLocation(new Point(0, 647));
        ((ViewableComponent)withName("pipeLineRand 8")).setPreferredLocation(new Point(138, 155));
        ((ViewableComponent)withName("pipeLineRand 24")).setPreferredLocation(new Point(6, 358));
        ((ViewableComponent)withName("pipeLineRand 100")).setPreferredLocation(new Point(50, 1520));
        ((ViewableComponent)withName("pipeLineRand 52")).setPreferredLocation(new Point(441, 559));
        ((ViewableComponent)withName("pipeLineRand 36")).setPreferredLocation(new Point(4, 578));
        ((ViewableComponent)withName("pipeLineRand 72")).setPreferredLocation(new Point(461, 752));
        ((ViewableComponent)withName("pipeLineRand 32")).setPreferredLocation(new Point(3, 491));
        ((ViewableComponent)withName("pipeLineRand 44")).setPreferredLocation(new Point(448, 390));
        ((ViewableComponent)withName("pipeLineRand 64")).setPreferredLocation(new Point(2, 791));
        ((ViewableComponent)withName("pipeLineRand 84")).setPreferredLocation(new Point(1, 1022));
        ((ViewableComponent)withName("pipeLineRand 16")).setPreferredLocation(new Point(15, 229));
        ((ViewableComponent)withName("pipeLineRand 28")).setPreferredLocation(new Point(1, 426));
        ((ViewableComponent)withName("pipeLineRand 48")).setPreferredLocation(new Point(441, 470));
        ((ViewableComponent)withName("pipeLineRand 40")).setPreferredLocation(new Point(475, 316));
        ((ViewableComponent)withName("pipeLineRand 88")).setPreferredLocation(new Point(395, 1021));
        ((ViewableComponent)withName("pipeLineRand 92")).setPreferredLocation(new Point(2, 1105));
        ((ViewableComponent)withName("pipeLineRand 76")).setPreferredLocation(new Point(420, 877));
        ((ViewableComponent)withName("pipeLineRand 20")).setPreferredLocation(new Point(9, 296));
        ((ViewableComponent)withName("pipeLineRand 60")).setPreferredLocation(new Point(3, 725));
        ((ViewableComponent)withName("pipeLineRand 12")).setPreferredLocation(new Point(289, 197));
        ((ViewableComponent)withName("pipeLineRand 4")).setPreferredLocation(new Point(34, 63));
        ((ViewableComponent)withName("pipeLineRand 68")).setPreferredLocation(new Point(451, 648));
        ((ViewableComponent)withName("pipeLineRand 80")).setPreferredLocation(new Point(8, 898));
    }
}
