
package  oneDCellSpace;

import java.lang.*;
import java.awt.*;
import java.io.*;
import java.util.*;
import simView.*;
import genDevs.modeling.*;
import genDevs.simulation.*;
import GenCol.*;
import genDevs.plots.*;
import pulseExpFrames.*;
import util.*;
import pulseModels.*;


public class workerOpt extends ViewableDigraph{



public workerOpt(){
this("workerOpt",1); //interference factor a
}

public workerOpt(String nm,double a){
super(nm);
addInport("in");
addOutport("out");

fireOnceNeuron n = new fireOnceNeuron("fn",0);
add(n);

varDisplay v = new varDisplay("time");
add(v);

double maxCrewSize = Math.min(35,1000/a);//for a>=1 this range contains the optimum

for (int i = 1;i<= maxCrewSize;i++){
ViewableDigraph w = new workCrew(i,a);
add(w);
//if (i != 3)
w.setBlackBox(true);
//w.setHidden(true);

addCoupling(w,"timeIs",n,"in");
addCoupling(w,"timeIs",v,"in");
addCoupling(n,"out",w,"stop");

}
}

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(653, 690);
        ((ViewableComponent)withName("workCrew16")).setPreferredLocation(new Point(421, 414));
        ((ViewableComponent)withName("workCrew18")).setPreferredLocation(new Point(257, 367));
        ((ViewableComponent)withName("workCrew30")).setPreferredLocation(new Point(-13, 512));
        ((ViewableComponent)withName("workCrew13")).setPreferredLocation(new Point(272, 408));
        ((ViewableComponent)withName("workCrew3")).setPreferredLocation(new Point(289, 483));
        ((ViewableComponent)withName("workCrew19")).setPreferredLocation(new Point(50, 311));
        ((ViewableComponent)withName("workCrew24")).setPreferredLocation(new Point(40, 543));
        ((ViewableComponent)withName("workCrew10")).setPreferredLocation(new Point(260, 232));
        ((ViewableComponent)withName("workCrew26")).setPreferredLocation(new Point(297, 582));
        ((ViewableComponent)withName("workCrew6")).setPreferredLocation(new Point(43, 427));
        ((ViewableComponent)withName("workCrew20")).setPreferredLocation(new Point(44, 194));
        ((ViewableComponent)withName("workCrew2")).setPreferredLocation(new Point(-2, 403));
        ((ViewableComponent)withName("fn")).setPreferredLocation(new Point(261, 37));
        ((ViewableComponent)withName("workCrew5")).setPreferredLocation(new Point(55, 155));
        ((ViewableComponent)withName("workCrew9")).setPreferredLocation(new Point(284, 448));
        ((ViewableComponent)withName("workCrew8")).setPreferredLocation(new Point(268, 338));
        ((ViewableComponent)withName("workCrew14")).setPreferredLocation(new Point(53, 121));
        ((ViewableComponent)withName("workCrew32")).setPreferredLocation(new Point(263, 160));
        ((ViewableComponent)withName("workCrew12")).setPreferredLocation(new Point(44, 281));
        ((ViewableComponent)withName("workCrew34")).setPreferredLocation(new Point(40, 467));
        ((ViewableComponent)withName("workCrew25")).setPreferredLocation(new Point(262, 120));
        ((ViewableComponent)withName("workCrew15")).setPreferredLocation(new Point(270, 619));
        ((ViewableComponent)withName("workCrew1")).setPreferredLocation(new Point(259, 304));
        ((ViewableComponent)withName("workCrew4")).setPreferredLocation(new Point(268, 200));
        ((ViewableComponent)withName("time")).setPreferredLocation(new Point(428, 54));
        ((ViewableComponent)withName("workCrew17")).setPreferredLocation(new Point(50, 50));
        ((ViewableComponent)withName("workCrew33")).setPreferredLocation(new Point(377, 484));
        ((ViewableComponent)withName("workCrew29")).setPreferredLocation(new Point(43, 606));
        ((ViewableComponent)withName("workCrew28")).setPreferredLocation(new Point(286, 551));
        ((ViewableComponent)withName("workCrew11")).setPreferredLocation(new Point(42, 247));
        ((ViewableComponent)withName("workCrew23")).setPreferredLocation(new Point(44, 378));
        ((ViewableComponent)withName("workCrew35")).setPreferredLocation(new Point(280, 519));
        ((ViewableComponent)withName("workCrew21")).setPreferredLocation(new Point(46, 349));
        ((ViewableComponent)withName("workCrew27")).setPreferredLocation(new Point(47, 219));
        ((ViewableComponent)withName("workCrew7")).setPreferredLocation(new Point(47, 507));
        ((ViewableComponent)withName("workCrew22")).setPreferredLocation(new Point(259, 267));
        ((ViewableComponent)withName("workCrew31")).setPreferredLocation(new Point(35, 570));
    }
}
