
package pulseModels;



import simView.*;
import genDevs.plots.*;
import java.awt.*;
import java.lang.*;
import genDevs.modeling.*;
import genDevs.simulation.*;
import GenCol.*;
import pulseExpFrames.*;
import java.util.*;

class momentumConserve extends differencer{
protected double loss;

public momentumConserve(double loss){
super("momentumConserve");
this.loss = loss;
}

public message out(){
if (inval<=0 && outval < 0)
return outputRealOnPort(loss,"out");
else return new message();
}
}

public class bouncingBall extends  ViewableDigraph{

public bouncingBall(){
this("bb",0,10,.2,.01);
addInport("stop");
}


public bouncingBall(String nm, double initPosition,
       double initVelocity, double loss, double quantum){
super(nm);

addInport("in");
addInport("stop");
addOutport("out");


ViewableAtomic gravity = new varGen("gravity",-10,1);
add(gravity);

addCoupling(this,"stop",gravity,"stop");

ViewableAtomic velocity = new sum("velocity",initVelocity);
add(velocity);
addCoupling(this,"in",velocity,"in");
addCoupling(gravity,"out",velocity,"in");


ViewableAtomic velocityGen = new varGen("velocityGen",initVelocity,quantum);
add(velocityGen);
addCoupling(velocity,"out",velocityGen,"setRate");

ViewableAtomic position = new sum("position",initPosition);
add(position);
addCoupling(velocityGen,"out",position,"in");

ViewableAtomic mc = new momentumConserve(loss);
add(mc);

addCoupling(position,"out",mc,"in");
addCoupling(mc,"out",velocity,"switchWLoss");



CellGridPlot timeP = new CellGridPlot("Position Plot",1,20);
timeP.setCellGridViewLocation(600,500);
timeP.setSpaceSize(100,40);
timeP.setCellSize(5);
timeP.setTimeScale(10);
add(timeP);

addCoupling(position,"out",timeP,"timePlot");//"pulsePlot");

}

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(549, 253);
        ((ViewableComponent)withName("velocityGen")).setPreferredLocation(new Point(-26, 98));
        ((ViewableComponent)withName("position")).setPreferredLocation(new Point(244, 110));
        ((ViewableComponent)withName("velocity")).setPreferredLocation(new Point(242, 29));
        ((ViewableComponent)withName("gravity")).setPreferredLocation(new Point(-20, 24));
        ((ViewableComponent)withName("momentumConserve")).setPreferredLocation(new Point(61, 176));
    }
}
