package pulseModels;

import simView.*;
import genDevs.plots.*;
import java.awt.*;
import java.lang.*;
import genDevs.modeling.*;
import genDevs.simulation.*;
import GenCol.*;
import pulseExpFrames.*;

import java.util.*;



public class boxCar extends  ViewableDigraph{

public boxCar(){
super("boxCar");

addInport("in");
addOutport("out");


ViewableAtomic basic = new basicGenr("basic",15,20,14,2,1,1000);
                              //dur1,dur2,dur3,p1,p2,p3

add(basic);


ViewableAtomic pg = new pulseGenr("pg");

add(pg);

addCoupling(basic,"out",pg,"setInterPulseTime");

CellGridPlot pulseP = new CellGridPlot("Pulse Plot",1,3);
pulseP.setCellGridViewLocation(600,250);
pulseP.setSpaceSize(100,40);
pulseP.setCellSize(5);
pulseP.setTimeScale(50);
add(pulseP);
pulseP.setHidden(false);

//addCoupling(basic,"out",pulseP,"pulsePlot");
addCoupling(pg,"out",pulseP,"pulsePlot");
/*
ViewableAtomic sum = new sum("sum",0);
add(sum);

addCoupling(pg,"out",sum,"in");

CellGridPlot timeP = new CellGridPlot("Sum Plot",1,200);
timeP.setCellGridViewLocation(600,500);
timeP.setSpaceSize(100,40);
timeP.setCellSize(5);
timeP.setTimeScale(50);
add(timeP);

addCoupling(sum,"out",timeP,"pulsePlot");
*/
}

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(705, 409);
        ((ViewableComponent)withName("sum")).setPreferredLocation(new Point(341, 25));
        ((ViewableComponent)withName("Pulse Plot")).setPreferredLocation(new Point(79, 84));
        ((ViewableComponent)withName("pg")).setPreferredLocation(new Point(267, 114));
        ((ViewableComponent)withName("basic")).setPreferredLocation(new Point(12, 4));
    }
}
