
package pulseModels;

import simView.*;
import genDevs.plots.*;
import java.awt.*;
import java.lang.*;
import genDevs.modeling.*;
import genDevs.simulation.*;
import GenCol.*;
import genDevs.modeling.*;
import SimpArc.*;
import pulseExpFrames.*;

public class distribGenr extends  ViewableDigraph{

public distribGenr(){
this("distribGenr",100,1000);
}

public distribGenr(String nm,double countInterval,int repetitions){
super(nm+ " countInterval= "+countInterval+ " repetitions= "+repetitions);
addInport("in");
addInport("start");
addOutport("outDist");
addTestInput("in",new doubleEnt(1),0);
addTestInput("start",new doubleEnt(10),0);
addTestInput("in",new doubleEnt(1),2);

ViewableAtomic g = new pulseGenr("genr",countInterval);//intarrivaltime
add(g);


ViewableAtomic gr = new pulseGenrRand("genrRand",10,1);//intarrivaltime,seed
add(gr);


ViewableAtomic cl = new myTimer("timer",countInterval*repetitions);//duration
add(cl);
addCoupling(cl,"out",g,"stop");
addCoupling(cl,"out",gr,"stop");


ViewableAtomic sf = new sum("sf");
add(sf);

addCoupling(gr,"out",sf,"in");
addCoupling(g,"out",sf,"reset");

ViewableAtomic sc = new statCollector("stat",10);//numClasses
add(sc);

addCoupling(sf,"outAccum",sc,"in");
addCoupling(sc,"outDist",this,"outDist");

}

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(739, 300);
        ((ViewableComponent)withName("sf")).setPreferredLocation(new Point(282, 155));
        ((ViewableComponent)withName("stat")).setPreferredLocation(new Point(426, 57));
        ((ViewableComponent)withName("genrRand")).setPreferredLocation(new Point(132, 38));
        ((ViewableComponent)withName("genr")).setPreferredLocation(new Point(-84, 33));
        ((ViewableComponent)withName("timer")).setPreferredLocation(new Point(49, 173));
    }
}
