
package pulseModels;

import simView.*;
import genDevs.modeling.*;
import genDevs.simulation.*;
import GenCol.*;

import java.util.*;
import java.awt.*;


public class duelist extends  ViewableDigraph{

public duelist(){
this("duelist",.4);
}

public duelist(String name,double timeToShoot){
super(name);

addInport("orderToShoot");
addInport("getHit");
addOutport("outShot");
addOutport("outDead");

addTestInput("orderToShoot",new entity());
addTestInput("orderToShoot",new entity(),.1);
addTestInput("getHit",new entity());
addTestInput("getHit",new entity(),.1);



ViewableAtomic shooter = new shooter("shooter",timeToShoot,.2);
ViewableAtomic deathProcess = new deathProcess("deathProcess",.3);

add(shooter);
add(deathProcess);

addCoupling(this,"orderToShoot",shooter,"orderToShoot");
addCoupling(this,"getHit",shooter,"getHit");
addCoupling(this,"getHit",deathProcess,"getHit");

addCoupling(deathProcess,"outDead",shooter,"getDead");
addCoupling(shooter,"outShot",this,"outShot");

addCoupling(deathProcess,"outDead",this,"outDead");
}

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(475, 215);
        ((ViewableComponent)withName("shooter")).setPreferredLocation(new Point(27, 44));
        ((ViewableComponent)withName("deathProcess")).setPreferredLocation(new Point(62, 143));
    }
}
