
package pulseModels;


import simView.*;
import genDevs.plots.*;
import java.awt.*;
import java.lang.*;
import genDevs.modeling.*;
import genDevs.simulation.*;
import GenCol.*;

import java.util.*;



public class gasReplace extends  ViewableDigraph{

public gasReplace(){
super("gasReplace");
this.setHidden(true);
addInport("in");
addOutport("out");

double fillRate = 2;//15;//20;// 1;
double lossRate = .01;//.05;//.1;//.01;
double ratio = fillRate/lossRate;//must be >99 to be allow solution
double quantum = 1;

ViewableDigraph methaneEvac = new feedback("methaneEvac",-lossRate,100,quantum);
add(methaneEvac);
//methaneEvac.setBlackBox(true);
//methaneEvac.setHidden(true);


ViewableAtomic pump = new varGen("pump",fillRate,quantum);
add(pump);


ViewableDigraph nitrogenFill = new feedback("nitrogenFill",-lossRate,0,quantum);
add(nitrogenFill);
nitrogenFill.setBlackBox(true);
addCoupling(pump,"out",nitrogenFill,"in");

CellGridPlot pulseP = new CellGridPlot("Methane Plot",1,300);
pulseP.setCellGridViewLocation(600,250);
pulseP.setSpaceSize(100,40);
pulseP.setCellSize(5);
pulseP.setTimeScale(300);
add(pulseP);

addCoupling(methaneEvac,"out",pulseP,"pulsePlot");

CellGridPlot timeP = new CellGridPlot("nitrogen Plot",1,500);
timeP.setCellGridViewLocation(600,500);
timeP.setSpaceSize(100,40);
timeP.setCellSize(5);
timeP.setTimeScale(300);
add(timeP);

addCoupling(nitrogenFill,"out",timeP,"pulsePlot");

ViewableDigraph ra = new ratioAcceptor(99);
add(ra);
ra.setBlackBox(true);

addCoupling(pump,"out",ra,"in");
addCoupling(nitrogenFill,"out",ra,"setDividend");
addCoupling(methaneEvac,"out",ra,"setDivisor");
addCoupling(ra,"stop",pump,"stop");
addCoupling(ra,"stop",nitrogenFill,"stop");
addCoupling(ra,"stop",methaneEvac,"stop");
addCoupling(ra,"out",this,"out");
/*

ViewableAtomic nitrogen = new sum("nitrogen",0);
add(nitrogen);

addCoupling(pump,"out",nitrogen,"in");
//addCoupling(nitrogen,"out",timeP,"pulsePlot");


ViewableAtomic d = new instantReal.divide("divide");
add(d);

addCoupling(nitrogenFill,"out",d,"setDividend");
addCoupling(methaneEvac,"out",d,"in");

ViewableAtomic thresh = new thresholdTester(99);
add(thresh);


addCoupling(d,"out",thresh,"in");
addCoupling(thresh,"out",pump,"stop");
addCoupling(thresh,"out",nitrogenFill,"stop");
*/

}

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(549, 253);
        ((ViewableComponent)withName("nitrogenFill")).setPreferredLocation(new Point(219, 34));
        ((ViewableComponent)withName("pump")).setPreferredLocation(new Point(-10, 55));
        ((ViewableComponent)withName("methaneEvac")).setPreferredLocation(new Point(202, 113));
        ((ViewableComponent)withName("ratioAcceptor")).setPreferredLocation(new Point(174, 179));
    }
}
