
package pulseModels;

import simView.*;
import genDevs.plots.*;
import java.awt.*;
import java.lang.*;
import genDevs.modeling.*;
import genDevs.simulation.*;
import GenCol.*;
import pulseExpFrames.*;

import java.util.*;



public class housePaint extends  ViewableDigraph{

public housePaint(){
super("housePaint");

addInport("in");
addOutport("out");
addOutport("timeIs");
addOutport("timeMark");


double quantum = 100;

ViewableAtomic MaryRate = new varGen("MaryRate",200,quantum);//rate 4800/24
ViewableAtomic JillRate = new varGen("JillRate",100,quantum);//rate 4800/48
                //combined rate is 300, so will take 4800/300 = 16 hours

ViewableAtomic houseBricks = new sum("houseBricks",0);//state,
ViewableAtomic MaryBricks = new sum("MaryBricks",0);
ViewableAtomic JillBricks = new sum("JillBricks",0);


add(MaryRate);
add(JillRate);

add(houseBricks);
add(MaryBricks);
add(JillBricks);

addCoupling(MaryRate,"out",MaryBricks,"in");
addCoupling(JillRate,"out",JillBricks,"in");

addCoupling(MaryRate,"out",houseBricks,"in");
addCoupling(JillRate,"out",houseBricks,"in");

CellGridPlot timeP = new CellGridPlot(name +" Time Plot",1,10000);
timeP.setCellGridViewLocation(100,500);
timeP.setSpaceSize(100,40);
timeP.setCellSize(5);
timeP.setTimeScale(50);
add(timeP);

addCoupling(MaryBricks,"out",timeP,"timePlot");
addCoupling(JillBricks,"out",timeP,"timePlot");
addCoupling(houseBricks,"out",timeP,"timePlot");

ViewableAtomic t = new thresholdTester(4800);
add(t);
addCoupling(houseBricks,"out",t,"in");

addCoupling(t,"out",MaryRate,"setRate");
addCoupling(t,"out",JillRate,"setRate");
}


    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(746, 339);
        ((ViewableComponent)withName("housePaint Time Plot")).setPreferredLocation(new Point(339, 234));
        ((ViewableComponent)withName("thresholdTester")).setPreferredLocation(new Point(394, 98));
        ((ViewableComponent)withName("MaryRate")).setPreferredLocation(new Point(-15, 174));
        ((ViewableComponent)withName("JillBricks")).setPreferredLocation(new Point(194, 23));
        ((ViewableComponent)withName("JillRate")).setPreferredLocation(new Point(-18, 31));
        ((ViewableComponent)withName("MaryBricks")).setPreferredLocation(new Point(196, 180));
        ((ViewableComponent)withName("houseBricks")).setPreferredLocation(new Point(199, 92));
    }
}
