package pulseModels;

import simView.*;
import genDevs.plots.*;
import java.awt.*;
import java.lang.*;
import genDevs.modeling.*;
import genDevs.simulation.*;
import GenCol.*;
import pulseExpFrames.*;


import java.util.*;


class crowdGen extends varGen{

public crowdGen(String nm,double initRate,double quantum){
super(nm,initRate,quantum);
}

public void deltext(double e,message x){
Continue(e);

 for (int i=0; i< x.getLength();i++)
   if (messageOnPort(x,"setRate",i)){
    doubleEnt dv = (doubleEnt)x.getValOnPort("setRate",i);
    if (dv.getv() <= 0)passivate();
    else
    rate = initRate*(1 - dv.getv()/4800);
   }
  double newTa = Math.abs(signedTimeAdvance());
  if (newTa < sigma)
  holdIn("active",newTa);
  else
  holdIn("active",sigma);//only to show level
}
}



public class housePaintCrowd extends  ViewableDigraph{

public housePaintCrowd(){
super("housePaintCrowd");

addInport("in");
addOutport("out");
addOutport("timeIs");
addOutport("timeMark");

int quantum = 100;

ViewableAtomic MaryRate = new crowdGen("MaryRate",200,quantum);//rate 4800/24
ViewableAtomic JillRate = new crowdGen("JillRate",100,quantum);//rate 4800/48
                //combined rate is 300, so will take 4800/300 = 16 hours

ViewableAtomic houseBricks = new sum("houseBricks",0);

add(MaryRate);
add(JillRate);

add(houseBricks);


addCoupling(MaryRate,"out",houseBricks,"in");
addCoupling(JillRate,"out",houseBricks,"in");

addCoupling(houseBricks,"out",MaryRate,"setRate");
addCoupling(houseBricks,"out",JillRate,"setRate");

CellGridPlot timeP = new CellGridPlot(name +" Time Plot",1,10000);
timeP.setCellGridViewLocation(100,500);
timeP.setSpaceSize(100,40);
timeP.setCellSize(5);
timeP.setTimeScale(100);
add(timeP);

addCoupling(houseBricks,"out",timeP,"pulsePlot");

ViewableAtomic t = new thresholdTester(4800);
add(t);

addCoupling(houseBricks,"out",t,"in");

ViewableAtomic cl = new stopWatch();
add(cl);
addCoupling(houseBricks,"out",cl,"start");

addCoupling(t,"out",cl,"stop");
addCoupling(t,"out",cl,"time?");

addCoupling(cl,"timeIs",this,"timeIs");

addCoupling(t,"out",cl,"time?");
addCoupling(t,"out",MaryRate,"setRate");
addCoupling(t,"out",JillRate,"setRate");
}

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(612, 392);
        ((ViewableComponent)withName("JillRate")).setPreferredLocation(new Point(5, 137));
        ((ViewableComponent)withName("stopWatch")).setPreferredLocation(new Point(17, 240));
        ((ViewableComponent)withName("MaryRate")).setPreferredLocation(new Point(10, 33));
        ((ViewableComponent)withName("houseBricks")).setPreferredLocation(new Point(243, 30));
        ((ViewableComponent)withName("thresholdTester")).setPreferredLocation(new Point(296, 116));
        ((ViewableComponent)withName("housePaintCrowd Time Plot")).setPreferredLocation(new Point(184, 204));
    }
}
