/*      Copyright 1999 Arizona Board of regents on behalf of
 *                  The University of Arizona
 *                     All Rights Reserved
 *         (USE & RESTRICTION - Please read COPYRIGHT file)
 *
 *  Version    : DEVSJAVA2.6
 *  Date       : 04-15-00
 */

package pulseModels;

import java.awt.*;
import simView.*;
import genDevs.modeling.*;
import genDevs.simulation.*;
import GenCol.*;

public class preyPredatorPatch extends ViewableDigraph{


public preyPredatorPatch(){
    super("preyPredatorPatch");

    ViewableAtomic g = new  preyPredator("p1",0,0);
    ViewableAtomic p = new  preyPredator("p2",0,0);

     add(g);
     add(p);


    addInport("in");
    addOutport("out");
    addTestInput("in",new entity(""));

    addCoupling(g,"gasp",p,"in");

     addCoupling(this,"in",g,"in");

     addCoupling(p,"out",this,"out");




}


    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(622, 341);
        ((ViewableComponent)withName("p1")).setPreferredLocation(new Point(83, 125));
        ((ViewableComponent)withName("p2")).setPreferredLocation(new Point(339, 103));
    }
}
