
package pulseModels;

import java.lang.*;
import java.awt.*;
import java.io.*;
import java.util.*;
import simView.*;
import genDevs.modeling.*;
import genDevs.simulation.*;
import GenCol.*;
import genDevs.plots.*;
import pulseExpFrames.*;

import statistics.*;

///////////////////////////////////

class singleTest extends ViewableDigraph{

public singleTest(){
this("unif",0,new randUniform(0));
}

public singleTest(String nm,int i,rand r){
super(nm);



ViewableAtomic pg =  new pulseExpFrames.pulseGenrRandSize(nm+i,1,0,r);
                //MUST HAVE different names for each when it
                //becomes component in larger system
add(pg);

ViewableAtomic ss =
         new statCollector("stat",10);
add(ss);

addCoupling(pg,"out",ss,"in");

ViewableAtomic cl = new myTimer("timer",1000);//duration
add(cl);

addCoupling(cl,"out",pg,"stop");

}

}
////////////////////////////////

public class randDistTest extends ViewableDigraph{

protected int numReps;


public randDistTest(){
this("randDistTest",3);
}

public randDistTest(String nm,int numReps){
super(nm);
addInport("in");
addOutport("out");
this.numReps = numReps;

for (int i = 0;i<numReps;i++){

  rand r =
  //new randPareto(i,1,1);
  //
  new randUniform(i);

  ViewableDigraph rdt = new singleTest("test"+i,i,r);

  add(rdt);
  }
}
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(756, 651);
        ((ViewableComponent)withName("test1")).setPreferredLocation(new Point(63, 190));
        ((ViewableComponent)withName("test0")).setPreferredLocation(new Point(63, 292));
        ((ViewableComponent)withName("test2")).setPreferredLocation(new Point(65, 32));
    }
}
