/*      Copyright 1999 Arizona Board of regents on behalf of
 *                  The University of Arizona
 *                     All Rights Reserved
 *         (USE & RESTRICTION - Please read COPYRIGHT file)
 *
 *  Version    : DEVSJAVA2.6
 *  Date       : 04-15-00
 */


package pulseModels;

import java.awt.*;
import genDevs.modeling.*;
import genDevs.simulation.*;
import simView.*;
import statistics.*;

//////////////////////////

class couplingControl extends ViewableAtomic{
protected randUniform r;
protected long seed;
protected boolean even;

    public couplingControl(String nm){
        super(nm);
        seed = 1;
    }

    public void initialize(){
     even = true;
    if (seed>1)   clearCouplings();
    r = new randUniform(seed++);
    sigma = 0;
    }

public void clearCouplings(){
removeCoupling("a1","out","b1","in");
removeCoupling("a1","out","b2","in");
removeCoupling("a1","out","b3","in");
removeCoupling("a2","out","b1","in");
removeCoupling("a2","out","b2","in");
removeCoupling("a2","out","b3","in");
removeCoupling("a3","out","b1","in");
removeCoupling("a3","out","b2","in");
removeCoupling("a3","out","b3","in");
}
public int pick(){
if (r.sample()<.33)
 return 1;
else if (r.sample()<.66)
 return 2;
else return 3;
}



    public void deltint()
    {
      if (even)
         removeCoupling("a1","out","b"+pick(),"in");
      else
         addCoupling("a1","out","b"+pick(),"in");

      if (!even)
         removeCoupling("a2","out","b"+pick(),"in");
      else
         addCoupling("a2","out","b"+pick(),"in");
               if (!even)

        removeCoupling("a3","out","b"+pick(),"in");
      else
         addCoupling("a3","out","b"+pick(),"in");

        if (even)
          even = false;
        else even = true;

         holdIn("active",10);

  }

}

class portAtomic extends ViewableAtomic{

public portAtomic(String name){
super(name);
addOutport("out");
addInport("in");
}
}

public class relationDemo extends ViewableDigraph {

public relationDemo (){
    super("relationDemo");

    ViewableAtomic a1 = new portAtomic("a1"); add(a1);
    ViewableAtomic b1 = new portAtomic("b1"); add(b1);
    ViewableAtomic a2 = new portAtomic("a2"); add(a2);
    ViewableAtomic b2 = new portAtomic("b2"); add(b2);
    ViewableAtomic a3 = new portAtomic("a3"); add(a3);
    ViewableAtomic b3 = new portAtomic("b3"); add(b3);

  ViewableAtomic tc = new couplingControl("tc");   add(tc);
  tc.setHidden(true);


 }




    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(598, 307);
        ((ViewableComponent)withName("b1")).setPreferredLocation(new Point(374, 42));
        ((ViewableComponent)withName("a1")).setPreferredLocation(new Point(46, 208));
        ((ViewableComponent)withName("b2")).setPreferredLocation(new Point(374, 124));
        ((ViewableComponent)withName("a3")).setPreferredLocation(new Point(42, 127));
        ((ViewableComponent)withName("b3")).setPreferredLocation(new Point(379, 202));
        ((ViewableComponent)withName("a2")).setPreferredLocation(new Point(45, 51));
    }
 }

