package twoDCellSpace;

import simView.*;
import genDevs.modeling.*;
import genDevs.simulation.*;
import genDevs.simulation.heapSim.HeapCoord;
import genDevs.simulation.realTime.*;
import genDevs.simulation.special.*;
import GenCol.*;
import genDevs.plots.*;
import java.util.*;
import java.awt.*;

import java.text.*;
import java.io.*;

public class lightSpreadCellSpace_newDisplay
    extends TwoDimCellSpace {
	
	newCellGridPlot plot;
	
  public lightSpreadCellSpace_newDisplay() {
    //
	    this(80, 40);
//    this(40, 40);
    // this(20,20);
  }

  public lightSpreadCellSpace_newDisplay(int xDim, int yDim) {
    super("LightSpread Cell Space", xDim, yDim);

    plot = new newCellGridPlot("lightSpreadCellSpace", 0.1,"", 800, "", 800);
    plot.setCellSize(5);
//    plot.getCellGridView().displayGrid=true;  // the grid is displayed as white
    plot.setCellGridViewLocation(570, 100);
    
    this.numCells = xDim * yDim;

    for (int i = 0; i < xDimCellspace; i++) {
      for (int j = 0; j < yDimCellspace; j++) {
    	  lightSpreadCell_newDisplay fc = new lightSpreadCell_newDisplay(i, j);
        //fc.visible = false;

        fc.barrierRect(25, 20, 4, 5);
        fc.barrierCircle(30, 23, 4);

        fc.barrierCircle(10, 10, 4);
        fc.barrierRect(5, 5, 4, 5);

        double rotAngle = Math.PI / 8;

        fc.barrierRectRotate(rotAngle, 4, 25, 2, 10);
        fc.barrierRectRotate(rotAngle, 8, 25, 2, 10);
        fc.barrierRectRotate(rotAngle, 2, 34, 10, 2);

        addCell(fc, xDimCellspace, yDimCellspace);
      }
    }

    lightSpreadCell_newDisplay c1 = (lightSpreadCell_newDisplay) withId(10, 15);
    c1.source = true;
    c1.period = 2;

    lightSpreadCell_newDisplay c2 = (lightSpreadCell_newDisplay) withId(33, 27);
//    c2.sink = true;
    c2.source = true;
    c2.period = 3;

    hideAll(); //hides only components so far

    // Do the couplings
    doNeighborToNeighborCoupling();
    coupleOneToAll(this, "stop", "stop");
    coupleOneToAll(this, "start", "start");

  }

  public static void main(String args[]){
  //CoordinatorInterface r;


//  coordinator r = new coordinator(new lightSpreadCellSpace_newDisplay());
//  HeapCoord r = new HeapCoord(new lightSpreadCellSpace_newDisplay());
  TunableCoordinator r = new TunableCoordinator(new lightSpreadCellSpace_newDisplay());
  r.setTimeScale(2);
  r.initialize();

  r.simulate(5000);
//  System.exit(0);
  }

  /**
   * Automatically generated by the SimView program.
   * Do not edit this manually, as such changes will get overwritten.
   */
  public void layoutForSimView() {
    preferredSize = new Dimension(900, 495);
    ( (ViewableComponent) withName("mover Cell_key = 20 ,value = 39")).
        setPreferredLocation(new Point(535, 59));
    ( (ViewableComponent) withName("Cell_key = 1 ,value = 0")).
        setPreferredLocation(new Point( -2, 62));
    ( (ViewableComponent) withName("mover Cell_key = 1 ,value = 1")).
        setPreferredLocation(new Point(548, 280));
    ( (ViewableComponent) withName("Cell_key = 1 ,value = 1")).
        setPreferredLocation(new Point(251, 60));
    ( (ViewableComponent) withName("Cell_key = 0 ,value = 1")).
        setPreferredLocation(new Point(260, 293));
    ( (ViewableComponent) withName("Cell_key = 0 ,value = 0")).
        setPreferredLocation(new Point( -2, 288));
  }
}
// End lightSpreadCellSpace
