package twoDCellSpace;

import java.awt.*;
import genDevs.simulation.*;

import genDevs.plots.*;
import simView.*;

public class virusSpreadCellSpace
    extends TwoDimCellSpace {

  public virusSpreadCellSpace() {
    //this(40, 40);
    // this(2,2);
    this(20, 20);
    // this(30,30);
  }

  public virusSpreadCellSpace(int xDim, int yDim) {
    super("virusSpread Cell Space", xDim, yDim);

    this.numCells = xDim * yDim;

    for (int i = 0; i < xDimCellspace; i++) {
      for (int j = 0; j < yDimCellspace; j++) {
        multiCell fc = new multiCell(i, j);
        addCell(fc, xDimCellspace, yDimCellspace);
      }
    }
    addCoupling(withId(19, 10), "start", withId(19, 19), "start");
    //
    hideAll(); //hides only components so far

    // Do the couplings

    doNeighborToNeighborCoupling();
    doNeighborToNeighborCoupling("infect");
    doNeighborToNeighborCoupling("anti");
    doNeighborToNeighborCoupling("ping");

    coupleOneToAll(this, "stop", "stop");
    coupleOneToAll(this, "start", "start");

    CellGridPlot t = new CellGridPlot("virusSpreadCellSpace", 0.1,
                                      "", 400, "", 400);

    t.setCellGridViewLocation(600, 300);
    t.setCellSize(10);
    t.setCellGridViewLocation(570, 100);
    add(t);
    // t.setHidden(false);
    coupleAllTo("outDraw", t, "drawCellToScale");

  }

  public static void main(String args[]){
  CoordinatorInterface r;


  r = new coordinator(new virusSpreadCellSpace());
  r.initialize();

  r.simulate(10000);
  System.exit(0);
  }


  /**
   * Automatically generated by the SimView program.
   * Do not edit this manually, as such changes will get overwritten.
   */
  public void layoutForSimView() {
    preferredSize = new Dimension(900, 1300);
    ( (ViewableComponent) withName("Cell_key = 0 ,value = 1")).
        setPreferredLocation(new Point(210, 43));
    ( (ViewableComponent) withName("Cell_key = 1 ,value = 0")).
        setPreferredLocation(new Point(51, 202));
    ( (ViewableComponent) withName("Cell_key = 0 ,value = 0")).
        setPreferredLocation(new Point(0, 28));
    ( (ViewableComponent) withName("Cell_key = 1 ,value = 1")).
        setPreferredLocation(new Point(50, 50));
  }
}
// End virusSpreadCellSpace
