package pulseExpFrames;



import simView.*;
import genDevs.plots.*;
import java.awt.*;
import java.lang.*;
import genDevs.modeling.*;
import genDevs.simulation.*;
import GenCol.*;

import java.util.*;



public class pulsePlot extends  ViewableDigraph{

public pulsePlot(){
super("pulsePlot");

addInport("in");
addOutport("out");


ViewableAtomic pulser1 = new pulseGenr("pulser1",1,.1);//interPulseTime,size

add(pulser1);


ViewableAtomic pulser2 = new pulseGenr("pulser2",10,1);

add(pulser2);

CellGridPlot pulseP = new CellGridPlot("Pulse Plot",1,3);
pulseP.setCellGridViewLocation(600,250);
pulseP.setSpaceSize(100,40);
pulseP.setCellSize(5);
pulseP.setTimeScale(50);
add(pulseP);

addCoupling(pulser1,"out",pulseP,"pulsePlot");
addCoupling(pulser2,"out",pulseP,"pulsePlot");

ViewableAtomic sum = new sum("sum",0);
add(sum);
addCoupling(pulser1,"out",sum,"in");
//addCoupling(pulser2,"out",sum,"in");

CellGridPlot timeP = new CellGridPlot("Sum Plot",1,100);
timeP.setCellGridViewLocation(600,500);
timeP.setSpaceSize(100,40);
timeP.setCellSize(5);
timeP.setTimeScale(50);
add(timeP);

addCoupling(sum,"out",timeP,"pulsePlot");
}
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(873, 532);
        ((ViewableComponent)withName("Sum Plot")).setPreferredLocation(new Point(35, 225));
        ((ViewableComponent)withName("pulser1")).setPreferredLocation(new Point(-24, 43));
        ((ViewableComponent)withName("sum")).setPreferredLocation(new Point(339, 76));
        ((ViewableComponent)withName("Pulse Plot")).setPreferredLocation(new Point(268, 208));
        ((ViewableComponent)withName("pulser2")).setPreferredLocation(new Point(-28, 145));
    }
}
