package quantization;
import simView.*;
import genDevs.modeling.*;
import genDevs.simulation.*;
import genDevs.plots.*;
import GenCol.*;
import java.util.*;
import java.awt.*;


public class oneDCompIntTest extends  ViewableDigraph{

public oneDCompIntTest (){
super("oneDCompIntTest ");

addInport("in");
addOutport("out");

addTestInput("in",new doubleEnt(0));
addTestInput("in",new doubleEnt(1));
addTestInput("in",new doubleEnt(-1));
addTestInput("in",new doubleEnt(.01));
addTestInput("in",new doubleEnt(-.01));

ViewableAtomic comp = new oneDCompInt("OneDCompInt",1,new sv(0,0));
add(comp);

addCoupling(this,"in",comp,"in");
addCoupling(comp,"out",this,"out");


CellGridPlot timeP = new CellGridPlot("Displacement Time Plot",10,500);
timeP.setCellGridViewLocation(100,300);
timeP.setSpaceSize(100,40);
timeP.setCellSize(5);
timeP.setTimeScale(50);

add(timeP);
addCoupling(comp,"out",timeP,"timePlot");
addCoupling(comp,"outV",timeP,"timePlot");
}

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(402, 175);
        ((ViewableComponent)withName("OneDCompInt")).setPreferredLocation(new Point(62, 46));
    }
}
