package quantization;
import simView.*;
import genDevs.modeling.*;
import genDevs.simulation.*;
import genDevs.plots.*;
import GenCol.*;
import java.util.*;
import java.awt.*;


public class twoDintTest extends  ViewableDigraph{

public twoDintTest (){
super("twoDintTest ");

addInport("in");
addOutport("out");


    double  root2 = 1/Math.sqrt(2);
    addTestInput("in",new vect2DEnt(0,0),0);
    addTestInput("in",new vect2DEnt(root2,root2),0);
    addTestInput("in",new vect2DEnt(root2,root2),.5);
    addTestInput("in",new vect2DEnt(-root2,root2),0);
    addTestInput("in",new vect2DEnt(root2,-root2),0);
    addTestInput("in",new vect2DEnt(-root2,-root2),0);
    addTestInput("in",new vect2DEnt(-root2,-root2),.5);


//ViewableAtomic comp = new twoDint("com",1,new vect2DEnt(0,0), Color.red);
ViewableAtomic comp = new twoDCompInt("twoDCompInt",1,
      new svVect(new vect2DEnt(0,0),new vect2DEnt(0,0)));

add(comp);

addCoupling(this,"in",comp,"in");

addCoupling(comp,"out",this,"out");


CellGridPlot t = new CellGridPlot( "Motion Plot",.1, 250,250);
t.setCellGridViewLocation(600,300);
add(t);


addCoupling(comp,"outDraw",t,"drawCellToScale");


CellGridPlot timeP = new CellGridPlot("Speed Time Plot",10,50);
timeP.setCellGridViewLocation(100,300);
timeP.setSpaceSize(100,40);
timeP.setCellSize(5);
timeP.setTimeScale(50);

add(timeP);
addCoupling(comp,"outSpeed",timeP,"timePlot");

}


    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(380, 202);
        ((ViewableComponent)withName("twoDCompInt")).setPreferredLocation(new Point(95, 68));
    }
}
